apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: justa 
  namespace: justa-teste
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justa
  targetCPUUtilizationPercentage: 80 # target CPU utilization